### PR TITLE
use a small, builtin default checkstyle config, fixes #3

### LINKED ISSUE #3: Default configuration
Currently it's a bit awkward: By default we show warnings for everything, then when generating a default configuration pretty much all warnings disappear.

It would be nice to have a more sensible default config that performs some basic checks but doesn't complain about too much nonsense.

### PR DESCRIPTION
**Pull request by AlexHaxe**
Warning: requires current git version of checkstyle!

### CODE REVIEW

**Comment by Gama11** [comment]
Is this the same as checkstyle's default config?

**Comment by AlexHaxe** [comment]
nope it's a small custom config, it doesn't have a lot of checks in it, but it's completely independant of checkstyle's internal defaults, so you can use your own style as a default for vscode-checkstyle.

I haven't figured out how to set a vscode configuration option with a default value, but it might be possible to include a complete checkstyle.json file as a default setting in vscode. So users could overwrite that setting without needing a physical checkstyle configuration file. Though, I don't now how realistic that scenario is, because currently vscode-checkstyle only runs on files you work on, so you still need a configuration file to let checkstyle run though your full source tree.

**Comment by Gama11** [comment]
The Haxe extension has a "Run Global Diagnostics" command, there could be something similar for vscode-checkstyle - perhaps even a setting to make that run automatically in the background on some set interval or something.

**Comment by AlexHaxe** [comment]
A full run might have some performance implications depending on the size of one's source tree.

It also needs to know what sources to include, you might have a local haxelib folder or some library in your project root, that doesn't work with your checkstyle config.
It happens even now, if you press `F12` on a type from Haxe's std lib, you will get a lot of checkstyle messages. But I guess that is a separate issue. (see #8)

**Comment by Gama11** [comment]
Just tested this... ouch:

**Comment by AlexHaxe** [comment]
Looks like something happened during AST generation. Can you post `Spawner.hx`? I guess there is something in there, that doesn't parse...

**Comment by Gama11** [comment]
https://github.com/HaxeFlixel/flixel-demos/blob/master/Platformers/Mode/source/Spawner.hx

**Comment by AlexHaxe** [comment]
Works fine with `"haxecheckstyle.configurationFile": ""` or set to something like `"haxecheckstyle.configurationFile": "notexisting.json"`

With `""` it would use the `checkstyle.json` of `vscode-checkstyle`, when set to something invalid, it uses checkstyle's builtin `addAllChecks` default.

But I am running on Linux, I guess you're on Windows, ~maybe there is a difference~,  yep definitely Windows...

**Comment by AlexHaxe** [comment]
I narrowed it down to this line: https://github.com/HaxeFlixel/flixel-demos/blob/dadf2c8aab315d26fadd1f73769937cc441373e1/Platformers/Mode/source/Spawner.hx#L118
It's the `new` keyword, I guess haxeparser version 3.3.0 doesn't have https://github.com/Simn/haxeparser/issues/38 

It worked for me, because I had a git version of haxeparser, that wasn't updated to current head - because that won't compile with haxe 3.4.7...

**Comment by Gama11** [comment]
Oh, so I just got really unlucky - that was the first file I checked. :) Strange results in other files too though:



Does it maybe expect spaces instead of tabs? If so, that error is a bit confusing.

**Comment by AlexHaxe** [comment]
I might have to change the phrasing for that check. 

As to the default, it's up to whoever makes the default, whether they prefer tabs or one, tow, three,etc spaces. But whatever you select it won't work for all users. When creating `checkystyle.json` in this pull request, I tried to guess the coding style of `vscode-checkstyle`, to make it pass its own defaults - it doesn't make sense to include defaults, that the project source doesn't adhere to.

**Comment by Gama11** [comment]
Could we auto-detect the indent of the current file to make it a bit less annoying for new users?

**Comment by AlexHaxe** [comment]
I think I am slightly ahead of you: https://github.com/HaxeCheckstyle/haxe-checkstyle/pull/409
:)

**Pull request merged**
