### PR TITLE
added json schema validation, fixes #11

### LINKED ISSUE #11: Provide a JSON schema for auto-completion in checkstyle.json
Right now configuration is a bit tedious due to the lack of auto-completion. VSCode extension can contribute a JSON schema that allows this. I've used this before to generate a schema for `vshaxe-build.json` files in the vshaxe-build extension:

- https://github.com/vshaxe/vshaxe-build/blob/031fccbd43cdb8b8210f75dbc19a6f3332d929fa/package.json#L38-L48
- https://github.com/vshaxe/vshaxe-build/blob/master/schemas/vshaxe-build-schema.json

The schema was auto-generated from the Haxe type definitions using @nadako's (not-quite-finished) library: https://github.com/nadako/haxe-type-to-json-schema

@AlexHaxe interested in working on this? :)

### PR DESCRIPTION
**Pull request by AlexHaxe**

### CODE REVIEW

**Comment by Gama11** [comment]
Oh, I didn't know that you could use a (web) URL there.. I wonder if that's a good idea, since that links to the dev branch, so the config might have properties that aren't yet in the current vscode-checkstyle release (once we start doing marketplace releases)?

Maybe it would be better to just include the config in the extension, since each checkstyle release is going to require a vscode-checkstyle release to go with it anyway? Since checkstyle is "compiled into" the extension.

**Comment by AlexHaxe** [comment]
It seems like there are a few properties missing from some of the checks. I will look into it and commit new schema files once I fixed it. So please don't merge yet...

**Comment by AlexHaxe** [comment]
New schema should now describe all fields and their values allowed in a checkstyle configuration file. 
At least VSCode doesn't find any violation with my `checkstyle.json` files.

**Comment by Gama11** [comment]
Seems to work nicely! 👍 

Two things I noticed that could be improved:

- None of the values and properties seem to have any documentation, it would be nice to have some info here about what each check does exactly for instance:

  

  If there's docs, they would be shown when hovering over a property and also in the completion details. I think nadako's schema generator actually had support for doc comments? At least some of the properties in vshaxe-build.json seem to have docs:

  

- If you select `type` from comletion, it auto-inserts `"Anonymous"` for some reason, even thought there's multiple options. Any idea why that is / do you set a default value for it?

**Comment by AlexHaxe** [comment]
Yes, doc support is still in there. I haven't tested it, mostly because there is a lack of documenting comments / annotations. 
I could add the contents of `@desc()` that briefly explains each check. More would require actual documentation.

I have seen `"type": "Anonymous"` but I'm not really sure why it does that. `Anonymous` is the first referenced item in the list of `anyOf` definitions, maybe it doesn't know any better.

**Comment by Gama11** [comment]
I think that would already be quite helpful. For the rest, maybe some content from the checkstyle website could be copied over?

**Pull request merged**
